### ISSUE TITLE
crossecore imports don't work and compiler errors.

### ISSUE THREAD

**Issue by redalertexpert** [crossecore/crossecore-generator#12]
Hi together,

when I generate typescript code with the crossecore-generator and the CROM.ecore model (this one [here](https://github.com/Eden-06/CROM/blob/master/org.rosi.crom.metamodel/model/crom_l1_composed.ecore)) I run into several problems. 

Firstly, the imports of crossecore don't seem to work since the follow the schema ```import {XXX} from "ecore/XXX";``` but should be ```import {XXX} from "crossecore";``` when crossecore is installed via npm. 

Secondly, some imports don't seem to work. Sometimes, the generator creates code that wants to import interfaces, that are implemented within the same class. I remove those imports by hand.

Illustration of both problems: (the import of CompartmentType is not needed here, and causes compiler errors)
![grafik](https://user-images.githubusercontent.com/12140954/83159999-ef9ad980-a106-11ea-8068-19c3a8d5adde.png)

At last, I had one compiler error in the ```Crom_l1_composedPackageImpl.ts``` where a propertiy is referenced that does not exist. 

![grafik](https://user-images.githubusercontent.com/12140954/83160500-92535800-a107-11ea-879e-3594c645bb22.png)

You can reproduce all errors by executing ```java -jar crossecore-generator_20200523-2248.jar -L typescript -e crom_l1_composed.ecore -p ./output/``` with the ecore model I referenced above.

Regards

**Comment by schwichti** [comment]
> Firstly, the imports of crossecore don't seem to work since the follow the schema import {XXX} > from "ecore/XXX"; but should be import {XXX} from "crossecore"; when crossecore is installed via > npm.

You need this TSconfig.json for the imports to work:
```json
{
 "compilerOptions": {
   "paths": {
     "ecore/*": ["node_modules/crossecore/lib/*"],
    },
 }
} 
```
See https://github.com/crossecore/crossecore-generator/blob/master/src/com/crossecore/typescript/TSConfigGenerator.xtend#L45

>Secondly, some imports don't seem to work. Sometimes, the generator creates code that wants to >import interfaces, that are implemented within the same class. I remove those imports by hand.
Have you tried the `typescript-fixes` branch? Maybe it solves some problems.

**Comment by redalertexpert** [comment]
Ok, the imports work now (I just had to add ```..``` to the tsconnfig.json) because I generated the code to a folder. 
The other compiler errors are still present while using the ```typescript-fixes``` branch. It seems to be a problem with enums. I created a very basic ecore file and generated code from it. (A Person which has a Nationality which is an enum). I get the following error:

![grafik](https://user-images.githubusercontent.com/12140954/83512804-078ca780-a4d1-11ea-9910-2ca49e329849.png)

Also the wrong import of the exported interface is still present. 

![grafik](https://user-images.githubusercontent.com/12140954/83512850-1ffcc200-a4d1-11ea-8f77-2138c6a8dbfe.png)

I attached the problematic file and the corresponding ecore file to reproduce it. 

[person.zip](https://github.com/crossecore/crossecore-generator/files/4716670/person.zip)

**Comment by schwichti** [comment]
There should be either ``initEDataType`` or ``initEEnum`` but not both. Obviously, the generator wrongfully generates ``initEDataType`` for ``EEnums`` because an ``EEnum`` is also an ``EDataType``.

Also, the generator needs to check if a referenced object is available in the currently generated class.

As you already did, you can simply delete the defective code lines until this is fixed in the generator.

**Comment by schwichti** [comment]
Should be fixed since https://github.com/crossecore/crossecore-generator/pull/22. Feel free to reopen issue.
