### ISSUE TITLE
Upload fat jar to Github Releases

### ISSUE THREAD

**Issue by krissrex** [crossecore/crossecore-generator#18]
If you could modify the CI pipeline to create a GitHub release with the jar, that would be helpful.
Then users don't have to build the project themselves.

**Comment by schwichti** [comment]
@krissrex can you support with this issue? Here is what I got so far: https://github.com/crossecore/crossecore-generator/blob/master/.github/workflows/release.yml

**Comment by schwichti** [comment]
You can now download the fatjar from the release assets: https://github.com/crossecore/crossecore-generator/releases/tag/v0.1.5
