### ISSUE TITLE
Don't import self in recursive types

### ISSUE THREAD

**Issue by krissrex** [crossecore/crossecore-generator#19]
I have a type `Node` with a `children` property also of type `Node`.
In the generated typescript code, the `Node.ts` is trying to import itself with `import {Node} from "mypackage/Node"`. 
This gives error: `Import declaration conflicts with local declaration of 'Node'.ts(2440)`.

Solution: alter the code generator to not import an interface, if that is the currently generated interface.

**Comment by krissrex** [comment]
It also seems to happen in `MypackagePackageImpl.ts`

**Comment by schwichti** [comment]
There is a fix for the generator on the testing branch: https://github.com/crossecore/crossecore-generator/commit/f7792a5b181153d59d11f5b3f510f47ab3103a71#

**Comment by schwichti** [comment]
Should be fixed since #22. Feel free to reopen issue.
