### ISSUE TITLE
Generated Typescript Factory is missing EFactory import

### ISSUE THREAD

**Issue by krissrex** [crossecore/crossecore-generator#20]
**Description:** Generated `*Factory.ts` is missing an import of `ecore/EFactory`.

**Actual:**
Inside `MypackageFactory.ts` you have the generated line:
`export interface MypackageFactory extends EFactory{`
but no import for the `EFactory`.

**Expected:**
The line `import { EFactory } from "ecore/EFactory";` should be present in the file.

**Comment by schwichti** [comment]
I pushed a fix to the testing branch: https://github.com/crossecore/crossecore-generator/commit/094e81d80548577f5b0e9a9f80337f115e4c51f4#diff-9ef56851de7e6b43516f3e6ee681232b1a7c0683a96e17d61a496ba491d928baR47

**Comment by schwichti** [comment]
Should be fixed since #22. Feel free to reopen issue.
