### ISSUE TITLE
Issue with model containing subpackages

### ISSUE THREAD

**Issue by jbmeyer** [crossecore/crossecore-generator#38]
Hello, 
I downloaded your code to test the generation of CSharp classes with an ecore model.
My model is containing a top package which contains several sub-packages ( which contains EClassifiers ). 
The generator is reading only the top package and not iterating of sub package. So the generation so containing only an empty top package.
Is this a limitation or is there a workaround to have the full model parsed ? 
Thanks

**Comment by schwichti** [comment]
Please see https://github.com/crossecore/crossecore-generator/issues/14
